version: '3'

services:
  app1:
    restart: always
    container_name: frandi
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: gunicorn myWeb.wsgi:application --bind 0.0.0.0:8003 --workers 2
