# Generated by Django 5.0.2 on 2024-05-12 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_artikel_judul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name_plural': '2. Artikel'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. ketegori'},
        ),
        migrations.AddField(
            model_name='artikel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
