# Generated by Django 5.0.2 on 2024-05-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
