version: '3'

services:
  app3:
    restart: always
    container_name: rifky
    environment:
      - TZ=Asia/Makassar
    build:
      context: .
    ports:
      - "8003:8003"
    volumes:
      - .:/app
    command: gunicorn latihanWeb.wsgi:application --bind 0.0.0.0:8003 --workers 2
